#-------------------------------
# General Site Settings
title: sooftware
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: Soohwan Kim
  image: code.gif
  say-hello: Hello, I’m <strong>Soohwan Kim</strong>
  bio: Current Co-founder & AI Research Engineer of TUNiB Inc. Previously at Kakao Brain. I majored in Electronic & Communication Engineering and minored in Data Science at Kwangwoon university. I hope to be a research engineer rather than a research scientist. My research interests include technologies for human-machine interaction, such as automatic speech recognition, speech synthesis, and natural language processing. I enjoy software development and sometimes like to write my knowledge or thoughts at my blog. I root for open-source culture, and I want to contribute. 
  #bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
facebook: https://facebook.com/sooftware95 # Add your Facebook handle
linkedin: https://linkedin.com/in/Soo-hwan/
github: https://github.com/sooftware/
twitter: https://twitter.com/SoohwanKim6 # Add your Twitter handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
